services:
  - type: web
    name: referral-system
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    healthCheckPath: /api/users
    autoDeploy: true
